github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/dailymotion-downloader/",
"https://serp.co/products/dailymotion-downloader/reviews/",
"https://extensions.serp.co/",
]
